//
// Created by GUILLAUME on 06/12/2017.
//

#ifndef SMART_RECEIPT_COM_ITSSF_SMART_RECEIPT_SCANNERACTIVITY_H
#define SMART_RECEIPT_COM_ITSSF_SMART_RECEIPT_SCANNERACTIVITY_H


class com_itssf_smart_receipt_ScannerActivity {

};


#endif //SMART_RECEIPT_COM_ITSSF_SMART_RECEIPT_SCANNERACTIVITY_H
