#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Django settings for smart_receipt project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+9dk*hunrmi&f2!)@nsr2yo)qmwqsmys0*cx^i0erb7br8^^%^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '192.168.232.129']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'smart_receipt'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'smart_receipt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_receipt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'smart_receipt',
	'USER' : 'smart_receipt_user',
	'PASSWORD' : 'olimex',
	'HOST' : '127.0.0.1',
	'PORT' : ''
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# media files pour les uploads et fichiers utilisateurs
# MEDIA_ROOT = '/home/guillaumefoucaudmi/trombinoscop/trombinoscop/media'
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


STATIC_URL = '/static/'

# STATIC_ROOT = '/home/guillaumefoucaudmi/trombinoscop/trombinoscop/static/'

STATICFILES_DIRS = (
	os.path.join(PROJECT_ROOT, 'static'),
	os.path.join(BASE_DIR, 'static'),
	PROJECT_ROOT,
	BASE_DIR
)


# définit les retour comme étant XHTML5 par défault
# DEFAULT_CONTENT_TYPE = 'application/xhtml+xml
# définit les retour comme étant HTML5 par défault'
DEFAULT_CONTENT_TYPE = 'text/html'
# définit l'encodage en utf-8 par défault
DEFAULT_CHARSET = 'utf-8'
# les session expire à la fermeture du navigateur
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


